<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <RootNamespace>BluetoothUnlock.ConfigUi</RootNamespace>
    <AssemblyName>BluetoothUnlock.ConfigUi</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BluetoothUnlock.Shared\BluetoothUnlock.Shared.csproj" />
  </ItemGroup>
</Project>
